# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0003_auto_20160729_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('banck', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coin', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Coin_Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios_exchange.Coin')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('url_icon', models.CharField(max_length=60)),
                ('type_wallet', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet', models.CharField(max_length=60)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios_exchange.Coin')),
                ('type_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios_exchange.Type_Wallet')),
            ],
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coin_wallet',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios_exchange.Wallet'),
        ),
    ]
