# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0005_auto_20160807_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
