# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('negocios_exchange', '0006_auto_20160807_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Cashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='banck',
            new_name='bank',
        ),
        migrations.AddField(
            model_name='bank_cashier',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios_exchange.Bank'),
        ),
        migrations.AddField(
            model_name='bank_cashier',
            name='cashier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
