# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0007_auto_20160807_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='coin',
        ),
        migrations.AddField(
            model_name='bank',
            name='account',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bank',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
