# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 04:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0008_auto_20160808_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_cashier',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
