# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0009_auto_20160808_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange_Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=80)),
                ('transaction_commission', models.FloatField()),
                ('cashier_commission', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('coin_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_1', to='negocios_exchange.Coin')),
                ('coin_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_2', to='negocios_exchange.Coin')),
            ],
        ),
        migrations.AddField(
            model_name='exchange_rate',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios_exchange.Transaction_Type'),
        ),
    ]
