# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0010_auto_20160808_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='dni',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='phone_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='phone_2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
