# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('negocios_exchange', '0011_auto_20160808_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField(default=0)),
                ('transaction_commission', models.FloatField()),
                ('cashier_commission', models.FloatField()),
                ('exchange_rate', models.FloatField()),
                ('code_coin_1', models.CharField(max_length=5)),
                ('code_coin_2', models.CharField(max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios_exchange.Bank')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier', to=settings.AUTH_USER_MODEL)),
                ('transaction_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier', to='negocios_exchange.Transaction_Status')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios_exchange.Transaction_Type')),
                ('type_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios_exchange.Type_Wallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='negocios_exchange.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios_exchange.Transaction')),
                ('transaction_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashiers', to='negocios_exchange.Transaction_Status')),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usero', to=settings.AUTH_USER_MODEL),
        ),
    ]
