# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0012_auto_20160808_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
