# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0013_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='code_confirmation_cashier',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='code_confirmation_user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashier', to=settings.AUTH_USER_MODEL),
        ),
    ]
