# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0016_auto_20160808_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_Entity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_entity', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type_wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_1', to='negocios_exchange.Bank'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_2', to='negocios_exchange.Bank'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_wallet_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_wallet_1', to='negocios_exchange.Type_Wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_wallet_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_wallet_2', to='negocios_exchange.Type_Wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_1', to='negocios_exchange.Wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_2', to='negocios_exchange.Wallet'),
        ),
        migrations.AddField(
            model_name='transaction_type',
            name='financial_entity_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_entity_1', to='negocios_exchange.Financial_Entity'),
        ),
        migrations.AddField(
            model_name='transaction_type',
            name='financial_entity_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_entity_2', to='negocios_exchange.Financial_Entity'),
        ),
    ]
