# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0019_auto_20160911_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_confirm',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
