# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0021_auto_20160911_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_1', to='negocios_exchange.Bank_Type'),
        ),
    ]
