# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0023_wallet_cashier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange_rate',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction_type',
            name='exchange_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wallet_cashier',
            name='type_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='negocios_exchange.Type_Wallet'),
        ),
        migrations.DeleteModel(
            name='Exchange_Rate',
        ),
    ]
