# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0024_auto_20161010_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_owner',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
