# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0025_bank_account_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='uid',
            field=models.CharField(default='', max_length=40),
        ),
    ]
