# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0026_user_profile_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='negocios_exchange.Country'),
        ),
    ]
