# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0028_wallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type_wallet_1',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type_wallet_2',
        ),
    ]
