# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0030_remove_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_1', to='negocios_exchange.Wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_wallet_1_', to='negocios_exchange.Wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_wallet_2_', to='negocios_exchange.Wallet'),
        ),
    ]
