# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0031_auto_20161024_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
    ]
