# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0032_remove_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_dni',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
