# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0034_auto_20161107_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_confirm',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction_confirm',
            name='financial_entity',
            field=models.CharField(default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_confirm',
            name='quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_confirm',
            name='type',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
