# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0036_auto_20161111_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
