# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0037_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ef1_commission',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ef2_commission',
            field=models.FloatField(null=True),
        ),
    ]
