# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0038_auto_20161115_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='commission',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='commission',
            field=models.FloatField(null=True),
        ),
    ]
