# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios_exchange', '0039_auto_20161115_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='commission',
        ),
        migrations.AddField(
            model_name='bank_type',
            name='commission',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='type_wallet',
            name='commission',
            field=models.FloatField(null=True),
        ),
    ]
